# Generated by Django 3.1.2 on 2022-07-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
